<?php

// Importame si es necesario
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5cabf049aa414',
	'title' => 'Datos adicionales del documento',
	'fields' => array(
		array(
			'key' => 'field_5cabf0532ab80',
			'label' => 'Datos adicionales',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5cabf0742ab81',
			'label' => 'Fecha de emisión',
			'name' => 'fecha_de_emision',
			'type' => 'date_picker',
			'instructions' => 'Indique la fecha de emisión del documento',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_5cabf09d2ab82',
			'label' => 'Archivo del documento',
			'name' => 'archivo_del_documento',
			'type' => 'file',
			'instructions' => 'Indique el archivo, en formato PDF del documento',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'pdf',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'resolucion',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'certificado',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'contrato',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5cd1beb3a28bd',
	'title' => 'Opciones de Inicio',
	'fields' => array(
		array(
			'key' => 'field_5cd1bebc0fab6',
			'label' => 'Láminas',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5cd1becb0fab7',
			'label' => 'Láminas',
			'name' => 'laminas',
			'type' => 'repeater',
			'instructions' => 'Muestra un carrusel de imágenes con texto, botones y enlaces',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Agregar lámina',
			'sub_fields' => array(
				array(
					'key' => 'field_5cd1c1fb464b6',
					'label' => 'Imagen',
					'name' => 'imagen',
					'type' => 'image',
					'instructions' => 'Imagen de la lámina',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'lamina',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5cd1c13b27ab8',
					'label' => 'Título',
					'name' => 'titulo',
					'type' => 'text',
					'instructions' => 'Indica un breve texto para el título',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5cd1c15427ab9',
					'label' => 'Descripción',
					'name' => 'descripcion',
					'type' => 'textarea',
					'instructions' => 'Indica un breve texto para la descripción',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_5cd1c17827aba',
					'label' => 'Enlace',
					'name' => 'enlace',
					'type' => 'link',
					'instructions' => 'Indica un enlace a algún elemento del sitio',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
				),
			),
		),
		array(
			'key' => 'field_5cd2f5a9a97cd',
			'label' => 'Cobertura',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5cd2f7182f53e',
			'label' => 'Texto descriptivo',
			'name' => 'texto_descriptivo',
			'type' => 'text',
			'instructions' => 'Indica un breve texto descriptivo para las zonas de cobertura.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5cd2f5b7a97ce',
			'label' => 'Zonas',
			'name' => 'zonas',
			'type' => 'repeater',
			'instructions' => 'Indique las zonas de cobertura a lo largo del país',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Agregar zona',
			'sub_fields' => array(
				array(
					'key' => 'field_5cd2f60da97d1',
					'label' => 'Imagen de la zona',
					'name' => 'imagen_de_la_zona',
					'type' => 'image',
					'instructions' => 'Indique una imagen descriptiva de la zona, se mostrará de fondo',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'zona',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5cd2f5dfa97cf',
					'label' => 'Nombre de la zona',
					'name' => 'nombre_de_la_zona',
					'type' => 'text',
					'instructions' => 'Indique el nombre de la zona',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5cd2f5f3a97d0',
					'label' => 'Nombre del representante',
					'name' => 'nombre_del_representante',
					'type' => 'text',
					'instructions' => 'Indique el nombre del representante de la zona',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5cd2f638a97d2',
					'label' => 'Correo electrónico del representante',
					'name' => 'correo_electronico_del_representante',
					'type' => 'email',
					'instructions' => 'Indique un correo electrónico del representante',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_5cd2f65aa97d3',
					'label' => 'Teléfono del representante',
					'name' => 'telefono_del_representante',
					'type' => 'text',
					'instructions' => 'Indique un número telefónico del representante en formato internacional',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5cd2ff3f7254b',
			'label' => 'Nuestra Empresa',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5cd2ff507254c',
			'label' => 'Contenido de nuestra empresa',
			'name' => 'contenido_de_nuestra_empresa',
			'type' => 'wysiwyg',
			'instructions' => 'Indique un breve texto para presentar a la empresa',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'visual',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_5cd2ff837254d',
			'label' => 'Imagen de nuestra empresa',
			'name' => 'imagen_de_nuestra_empresa',
			'type' => 'image',
			'instructions' => 'Indique una imagen descriptiva de la empresa',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5cd303f45df62',
			'label' => 'Destrezas',
			'name' => 'destrezas',
			'type' => 'repeater',
			'instructions' => 'Indica destrezas de la empresa visibles sólo en la página de inicio',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Agregar destreza',
			'sub_fields' => array(
				array(
					'key' => 'field_5cd304727f5cd',
					'label' => 'Título de la destreza',
					'name' => 'titulo_de_la_destreza',
					'type' => 'text',
					'instructions' => 'Indique un breve título de la destreza',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5cd304987f5ce',
					'label' => 'Icono de la destreza',
					'name' => 'icono_de_la_destreza',
					'type' => 'image',
					'instructions' => 'Indique un ícono para esta destreza',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5cd304c97f5cf',
					'label' => 'Descripción de la destreza',
					'name' => 'descripcion_de_la_destreza',
					'type' => 'textarea',
					'instructions' => 'Indique una breve descripción para la destreza',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
				),
			),
		),
		array(
			'key' => 'field_5cd309c4403ad',
			'label' => 'Calidad',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5cd30a7a403ae',
			'label' => 'Texto de la sección calidad',
			'name' => 'texto_de_la_seccion_calidad',
			'type' => 'wysiwyg',
			'instructions' => 'Indique un texto para la sección calidad',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'visual',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_5cd30aaf403af',
			'label' => 'Galería de la sección calidad',
			'name' => 'galeria_de_la_seccion_calidad',
			'type' => 'gallery',
			'instructions' => 'Indique un par de imágenes para la sección',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => 2,
			'insert' => 'append',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-inicio.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'revisions',
		6 => 'slug',
		7 => 'author',
		8 => 'format',
		9 => 'page_attributes',
		10 => 'featured_image',
		11 => 'categories',
		12 => 'tags',
		13 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5cd45578433e1',
	'title' => 'Opciones de página Área Clientes',
	'fields' => array(
		array(
			'key' => 'field_5cd4558d20027',
			'label' => 'Área Clientes',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5cd455a820028',
			'label' => 'Texto área clientes',
			'name' => 'texto_area_clientes',
			'type' => 'wysiwyg',
			'instructions' => 'Indique un texto explicativo del área de clientes',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'visual',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-clientes.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5cd4348c9b92a',
	'title' => 'Opciones de página Servicios',
	'fields' => array(
		array(
			'key' => 'field_5cd434c285531',
			'label' => 'Metodología',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5cd4361a85532',
			'label' => 'Metodologías',
			'name' => 'metodologias',
			'type' => 'repeater',
			'instructions' => 'Metodologías que se usan',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5cd4363c85533',
					'label' => 'Icono de la metodología',
					'name' => 'icono_de_la_metodologia',
					'type' => 'image',
					'instructions' => 'Indique ícono de la metodología',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5cd4365d85534',
					'label' => 'Título de la metodología',
					'name' => 'titulo_de_la_metodologia',
					'type' => 'text',
					'instructions' => 'Indique título de la metodología',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5cd4367585535',
					'label' => 'Texto de la metodología',
					'name' => 'texto_de_la_metodologia',
					'type' => 'textarea',
					'instructions' => 'Indique un breve texto para describir esta metodología',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-servicios.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c8af7a33be09',
	'title' => 'Opciones del servicio',
	'fields' => array(
		array(
			'key' => 'field_5c8af7abe0129',
			'label' => 'Imagen',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5c8af7b9e012a',
			'label' => 'Imagen referencial',
			'name' => 'imagen_referencial',
			'type' => 'image',
			'instructions' => 'Indica una imagen referencial para este servicio',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'service-reference',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'servicio',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5cd072014cb3a',
	'title' => 'Opciones generales',
	'fields' => array(
		array(
			'key' => 'field_5cd0721bff7bc',
			'label' => 'Contacto',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5cd0722eff7bd',
			'label' => 'Correo electrónico',
			'name' => 'correo_electronico',
			'type' => 'email',
			'instructions' => 'Indique el correo electrónico de contacto',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_5cd0724fff7be',
			'label' => 'Teléfono',
			'name' => 'telefono',
			'type' => 'text',
			'instructions' => 'Indique el número telefónico de contacto en formato internacional',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5cd0a2a9afb17',
			'label' => 'Dirección',
			'name' => 'direccion',
			'type' => 'text',
			'instructions' => 'Dirección de la Casa Matriz',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'opciones-generales',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5cd354ddeb87c',
	'title' => 'Opciones Página Empresa',
	'fields' => array(
		array(
			'key' => 'field_5cd354f58fc9c',
			'label' => 'Misión',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5cd355018fc9d',
			'label' => 'Imagen de la Misión',
			'name' => 'imagen_de_la_mision',
			'type' => 'image',
			'instructions' => 'Indique una imagen para la Misión',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5cd364e08ffd3',
			'label' => 'Texto de la Misión',
			'name' => 'texto_de_la_mision',
			'type' => 'textarea',
			'instructions' => 'Indique un breve texto para la misión',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5cd364fab8417',
			'label' => 'Visión',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5cd3650ab8418',
			'label' => 'Imagen de la Visión',
			'name' => 'imagen_de_la_vision',
			'type' => 'image',
			'instructions' => 'Indique una imagen para la visión',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5cd36523b8419',
			'label' => 'Texto de la Visión',
			'name' => 'texto_de_la_vision',
			'type' => 'textarea',
			'instructions' => 'Indique un breve texto para la visión',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5cd36aad51893',
			'label' => 'Política de Calidad',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5cd36abe51894',
			'label' => 'Texto antes de la política de calidad',
			'name' => 'texto_antes_de_la_politica_de_calidad',
			'type' => 'text',
			'instructions' => 'Indique un texto para la política de calidad',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5cd41f7b55084',
			'label' => 'Políticas',
			'name' => 'politicas',
			'type' => 'repeater',
			'instructions' => 'Indique las políticas de Calidad.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Agregar política',
			'sub_fields' => array(
				array(
					'key' => 'field_5cd41fab55085',
					'label' => 'Icono de la politica',
					'name' => 'icono_de_la_politica',
					'type' => 'image',
					'instructions' => 'Icono de la política de calidad',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5cd41fbb55086',
					'label' => 'Texto de la política',
					'name' => 'texto_de_la_politica',
					'type' => 'text',
					'instructions' => 'Breve texto de la política de calidad',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5cd4201555087',
			'label' => 'Texto después de la política de calidad',
			'name' => 'texto_despues_de_la_politica_de_calidad',
			'type' => 'text',
			'instructions' => 'Indique un texto para la política de calidad',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-empresa.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;